### ISSUE TITLE
Cannot add a paper from arxiv

### ISSUE THREAD

**Issue by bejito** [bobinette/papernet#19]
When I search for a paper on the arxiv tab (search for `A new quantum ripple-carry addition circuit`), I find the paper but when I click on `see on papernet`, I just end up on the page of one of my other papers, without having the paper added to my space

**Comment by bobinette** [comment]
I'll have a look into it ASAP. It sounds like the reconciliation is not properly done anymore between the arxiv id and the paper id

**Comment by bobinette** [comment]
I found the problem: the entry ID of the paper you are searching for is `http://arxiv.org/abs/quant-ph/0410184v1`, however my regex for reconciliation is `http://arxiv.org/abs/([0-9.]*)(v[0-9]+)?`, which does not match because of the `quant-ph` in the middle. I'll try to come up with either a better regex or a smarter way to extract the id.

**Comment by bejito** [comment]
This should do the job: 
https://github.com/bobinette/papernet/pull/22
